server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_service
    username: postgres
    password: admin   # change selon ton mot de passe
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cr√©e les tables automatiquement (dev mode)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  secret: ton_secret_jwt
