apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-moderation-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-moderation-backend
  template:
    metadata:
      labels:
        app: admin-moderation-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: admin-moderation-backend
          image: ghcr.io/OWNER/admin-moderation-backend:ci
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-postgresql:5432/adminmod
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: adminpass
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
