apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-moderation-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-moderation-backend
  template:
    metadata:
      labels:
        app: admin-moderation-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: admin-moderation-backend
          image: ghcr.io/OWNER/admin-moderation-backend:ci-${GITHUB_SHA}
          ports:
            - containerPort: 8080
