apiVersion: v1
kind: Service
metadata:
  name: admin-moderation-backend-service
spec:
  type: NodePort
  selector:
    app: admin-moderation-backend
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
